# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 256)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(350, 50, 88, 28))
        self.calculateButton.setObjectName("calculateButton")
        self.inputIntervalLeft = QtWidgets.QLineEdit(self.centralwidget)
        self.inputIntervalLeft.setGeometry(QtCore.QRect(180, 20, 161, 28))
        self.inputIntervalLeft.setInputMask("")
        self.inputIntervalLeft.setObjectName("inputIntervalLeft")
        self.inputIntervalRight = QtWidgets.QLineEdit(self.centralwidget)
        self.inputIntervalRight.setGeometry(QtCore.QRect(180, 50, 161, 28))
        self.inputIntervalRight.setInputMask("")
        self.inputIntervalRight.setText("")
        self.inputIntervalRight.setObjectName("inputIntervalRight")
        self.inputAccuracity = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAccuracity.setGeometry(QtCore.QRect(180, 80, 161, 28))
        self.inputAccuracity.setInputMask("")
        self.inputAccuracity.setText("")
        self.inputAccuracity.setMaxLength(32767)
        self.inputAccuracity.setFrame(True)
        self.inputAccuracity.setObjectName("inputAccuracity")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 161, 20))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 161, 20))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 151, 20))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(450, 10, 171, 121))
        self.textBrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textBrowser.setObjectName("textBrowser")
        self.outputRoot = QtWidgets.QLineEdit(self.centralwidget)
        self.outputRoot.setEnabled(True)
        self.outputRoot.setGeometry(QtCore.QRect(70, 170, 121, 28))
        self.outputRoot.setReadOnly(True)
        self.outputRoot.setPlaceholderText("")
        self.outputRoot.setObjectName("outputRoot")
        self.outputValue = QtWidgets.QLineEdit(self.centralwidget)
        self.outputValue.setEnabled(True)
        self.outputValue.setGeometry(QtCore.QRect(200, 170, 121, 28))
        self.outputValue.setReadOnly(True)
        self.outputValue.setPlaceholderText("")
        self.outputValue.setObjectName("outputValue")
        self.outputIterations = QtWidgets.QLineEdit(self.centralwidget)
        self.outputIterations.setEnabled(True)
        self.outputIterations.setGeometry(QtCore.QRect(330, 170, 121, 28))
        self.outputIterations.setReadOnly(True)
        self.outputIterations.setPlaceholderText("")
        self.outputIterations.setObjectName("outputIterations")
        self.outputErrorCode = QtWidgets.QLineEdit(self.centralwidget)
        self.outputErrorCode.setEnabled(True)
        self.outputErrorCode.setGeometry(QtCore.QRect(460, 170, 121, 28))
        self.outputErrorCode.setReadOnly(True)
        self.outputErrorCode.setPlaceholderText("")
        self.outputErrorCode.setObjectName("outputErrorCode")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 150, 121, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 150, 121, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 150, 121, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 150, 121, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputIntervalLeft, self.inputIntervalRight)
        MainWindow.setTabOrder(self.inputIntervalRight, self.inputAccuracity)
        MainWindow.setTabOrder(self.inputAccuracity, self.calculateButton)
        MainWindow.setTabOrder(self.calculateButton, self.outputRoot)
        MainWindow.setTabOrder(self.outputRoot, self.outputValue)
        MainWindow.setTabOrder(self.outputValue, self.outputIterations)
        MainWindow.setTabOrder(self.outputIterations, self.outputErrorCode)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculateButton.setText(_translate("MainWindow", "Рассчитать"))
        self.label.setText(_translate("MainWindow", "Левая граница отрезка"))
        self.label_2.setText(_translate("MainWindow", "Правая граница отрезка"))
        self.label_4.setText(_translate("MainWindow", "Точность"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тексты ошибок:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0 - успешное завершение</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 - корень не найден</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2 - превышено максимальное число итераций</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3 - деление на ноль</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Корень"))
        self.label_6.setText(_translate("MainWindow", "Значение функции"))
        self.label_7.setText(_translate("MainWindow", "Итерации"))
        self.label_8.setText(_translate("MainWindow", "Код ошибки"))
